apiVersion: v1
kind: Service
metadata:
  name: web-java
  labels:
    app: webjava
spec:
  type: LoadBalancer  
  ports:
  - name: http    
    port: 80
    targetPort: 8080
    protocol: TCP    
  selector:
    app: webjava
